# Generated by Django 3.0.8 on 2020-08-05 19:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_realtor', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealtorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('comment', models.TextField(blank=True)),
                ('posted_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rater', to='accounts.Account')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realtor', to='accounts.Account')),
            ],
        ),
    ]
