# Generated by Django 3.0.8 on 2020-07-26 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '__first__'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedinfo', models.CharField(max_length=200)),
                ('entrance_date', models.DateTimeField(blank=True)),
                ('exit_date', models.DateTimeField(blank=True)),
                ('deal_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to='accounts.Account')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='host', to='accounts.Account')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Listing')),
            ],
        ),
    ]
